apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 2  # Number of pod replicas (change this as needed)
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-container
        image: your-dockerhub-username/react-app  # Use your image name here
        ports:
        - containerPort: 3000
