apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 3000  # Port on which the app is running in the container
